<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('tbllocalstatistics', function (Blueprint $table) {
            $table->id();
            $table->string('RecYear');
            $table->string('RecMonth');
            $table->string('RecDate');
            $table->string('CMemM');
            $table->string('CMemF');
            $table->string('TCMem');
            $table->string('TMale')->nullable();
            $table->string('TFem')->nullable();
            $table->string('TTot')->nullable();
            $table->string('YMale')->nullable();
            $table->string('YFem')->nullable();
            $table->string('YTot')->nullable();
            $table->string('YotMM')->nullable();
            $table->string('YotMF')->nullable();
            $table->string('YotMT')->nullable();
            $table->string('OTAM')->nullable();
            $table->string('OTAF')->nullable();
            $table->string('OTAT')->nullable();
            $table->string('TAM')->nullable();
            $table->string('OM')->nullable();
            $table->string('M')->nullable();
            $table->string('MW')->nullable();
            $table->string('RM')->nullable();
            $table->string('RMW')->nullable();
            $table->string('ED')->nullable();
            $table->string('D')->nullable();
            $table->string('DC')->nullable();
            $table->string('LL')->nullable();
            $table->string('OR1')->nullable();
            $table->string('ASW')->nullable();
            $table->string('GS')->nullable();
            $table->string('HUM')->nullable();
            $table->string('MPWD')->nullable();
            $table->string('NC')->nullable();
            $table->string('HS')->nullable();
            $table->string('OAHS')->nullable();
            $table->string('TE')->nullable();
            $table->string('YA')->nullable();
            $table->string('OA')->nullable();
            $table->string('TT')->nullable();
            $table->string('T')->nullable();
            $table->string('YAO')->nullable();
            $table->string('OAA')->nullable();
            $table->string('TTT')->nullable();
            $table->string('BW')->nullable();
            $table->string('BBF')->nullable();
            $table->string('AD')->nullable();
            $table->string('HCC')->nullable();
            $table->string('HCM')->nullable();
            $table->string('HCF')->nullable();
            $table->string('HCTT')->nullable();
            $table->string('HCMM')->nullable();
            $table->string('BS')->nullable();
            $table->string('BST')->nullable();
            $table->string('MBS')->nullable();
            $table->string('MBSH')->nullable();
            $table->text('PBR')->nullable();
            $table->text('ACA')->nullable();
            $table->text('AMA')->nullable();
            $table->text('ACAA')->nullable();
            $table->text('ALS')->nullable();
            $table->text('NCC')->nullable();
            $table->text('NCR')->nullable();
            $table->text('EVNC')->nullable();
            $table->text('NCCH')->nullable();
            $table->text('MIW')->nullable();
            $table->text('WAA')->nullable();
            $table->text('WCPM')->nullable();
            $table->text('AA4WCPM')->nullable();
            $table->text('HGP')->nullable();
            $table->text('TOM')->nullable();
            $table->text('BMM')->nullable();
            $table->text('ACJS')->nullable();
            $table->text('CDD')->nullable();
            $table->text('CWC')->nullable();
            $table->text('CBHS')->nullable();
            $table->text('CBW')->nullable();
            $table->text('CMT')->nullable();
            $table->text('CAND')->nullable();
            $table->text('CTTRI')->nullable();
            $table->text('CTTRO')->nullable();
            $table->text('Birth')->nullable();
            $table->text('CDeath')->nullable();
            $table->text('NClassesW')->nullable();
            $table->text('NClassesM')->nullable();
            $table->text('NClassesY')->nullable();
            $table->text('NClassesE')->nullable();
            $table->text('NClassesC')->nullable();
            $table->text('AverageAW')->nullable();
            $table->text('AverageAM')->nullable();
            $table->text('AverageAY')->nullable();
            $table->text('AverageAE')->nullable();
            $table->text('AverageAC')->nullable();
            $table->text('VisitMW')->nullable();
            $table->text('VisitMM')->nullable();
            $table->text('VisitMY')->nullable();
            $table->text('VisitME')->nullable();
            $table->text('VisitMC')->nullable();
            $table->text('56HUM')->nullable();
            $table->text('56MP')->nullable();
            $table->text('57HUM')->nullable();
            $table->text('57MP')->nullable();
            $table->text('58HUM')->nullable();
            $table->text('58MP')->nullable();
            $table->text('Disab')->nullable();
            $table->text('60a')->nullable();
            $table->text('60b')->nullable();
            $table->text('60c')->nullable();
            $table->text('60d')->nullable();
            $table->text('60e')->nullable();
            $table->text('60f')->nullable();
            $table->text('60g')->nullable();
            $table->text('61a')->nullable();
            $table->text('61b')->nullable();
            $table->text('61c')->nullable();
            $table->text('61d')->nullable();
            $table->text('61di')->nullable();
            $table->text('61dii')->nullable();
            $table->text('61diii')->nullable();
            $table->text('61div')->nullable();
            $table->text('61e')->nullable();
            $table->text('61fy')->nullable();
            $table->text('61fn')->nullable();
            $table->text('62a')->nullable();
            $table->text('62b')->nullable();
            $table->text('62c')->nullable();
            $table->text('62d')->nullable();
            $table->text('62e')->nullable();
            $table->text('62f')->nullable();
            $table->text('62g')->nullable();
            $table->text('62h')->nullable();
            $table->text('62oth')->nullable();
            $table->text('ChurchID')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('tbllocalstatistics');
    }
};
